import path from "path";
import type { BlogPostMeta } from "./types";

/**
 * 公開記事レジストリ
 *
 * キー = 公開 URL の slug（/blog/[slug]）
 * contentId = 管理用フォルダ名（content/blog/[contentId]/）
 *
 * フォルダ運用（3層）・markdownFile 命名: docs/ai-context/content-folders.md
 * - 新規1分Tips: contentId "20-investigate-something"（量産インボックス）
 * - シリーズ確定: A層（01, 02, 03, 04, 08 等）へ昇格時は contentId のみ更新（slug 不変）
 *
 * 新規記事の追加手順:
 * 1. content/blog/20-investigate-something/ に Markdown を置く（昇格済みシリーズは該当 A層）
 * 2. public/images/blog/... に画像を置く（imageBasePath）
 * 3. 下記に1件追加
 */
export const blogPosts = {
  "site-launch": {
    contentId: "01-site-launch",
    markdownFile: "001-site-launch-draft-v3.md",
    imageBasePath: "/images/blog/site-launch",
    publishedAt: "2026-05-20",
    ogImage: "01-success-webpage.png",
    category: "devops",
  },
  "claude-obsidian-workflow": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "001-claude-obsidian-workflow-published.md",
    imageBasePath: "/images/blog/claude-obsidian-workflow",
    publishedAt: "2026-05-20",
    ogImage: "08-cursor-create-webpage.png",
    category: "ai-workflow",
  },
  "ai-role-sharing-workflow": {
    contentId: "01-site-launch",
    markdownFile: "002-claude-ai-role-sharing-workflow-revised.md",
    imageBasePath: "/images/blog/ai-role-sharing-workflow",
    publishedAt: "2026-05-22",
    ogImage: "og.png",
    category: "ai-workflow",
    layout: "rich-toc",
  },
  "source-md-ai-writing": {
    contentId: "01-site-launch",
    markdownFile: "003-source-md-ai-writing-revised.md",
    imageBasePath: "/images/blog/source-md-ai-writing",
    publishedAt: "2026-05-22",
    ogImage: "og.png",
    category: "ai-workflow",
    layout: "rich-toc",
  },
  "vercel-domain-invalid-nameserver": {
    contentId: "01-site-launch",
    markdownFile: "004-vercel-domain-invalid-nameserver.md",
    imageBasePath: "/images/blog/vercel-domain-invalid-nameserver",
    publishedAt: "2026-05-22",
    ogImage: "01-vercel-invalid.png",
    category: "devops",
    layout: "rich-toc",
  },
  "captions-md-workflow": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "002-captions-md-workflow.md",
    imageBasePath: "/images/blog/captions-md-workflow",
    publishedAt: "2026-05-24",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "obsidian-daily-notes-workflow": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "006-obsidian-daily-notes-workflow-final.md",
    imageBasePath: "/images/blog/obsidian-daily-notes-workflow",
    publishedAt: "2026-05-24",
    ogImage: "06-image1.png",
    category: "ai-workflow",
  },
  "ai-docs-duplication-tips": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "008-ai-docs-duplication-tips.md",
    imageBasePath: "/images/blog/claude-obsidian-workflow",
    publishedAt: "2026-05-27",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "obsidian-daily-notes-ai-log": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "007-obsidian-daily-notes-ai-log.md",
    imageBasePath: "/images/blog/obsidian-daily-notes-ai-log",
    publishedAt: "2026-05-27",
    ogImage: "og.svg",
    category: "ai-workflow",
  },
  "obsidian-checkbox-shortcut-ctrl-l": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "009-obsidian-checkbox-shortcut-ctrl-l.md",
    imageBasePath: "/images/blog/obsidian-checkbox-shortcut-ctrl-l",
    publishedAt: "2026-05-27",
    ogImage: "og.svg",
    category: "ai-workflow",
  },
  "captions-md-tips": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "003-captions-md-tips.md",
    imageBasePath: "/images/blog/claude-obsidian-workflow",
    publishedAt: "2026-05-28",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "source-md-tips": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "005-source-md-tips.md",
    imageBasePath: "/images/blog/claude-obsidian-workflow",
    publishedAt: "2026-05-28",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "ai-screenshot-caption-tips": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "004-screenshots-captions-tips.md",
    imageBasePath: "/images/blog/claude-obsidian-workflow",
    publishedAt: "2026-05-28",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-free": {
    contentId: "03-cursor-free",
    markdownFile: "001-cursor-free-plan-review_20260525.md",
    imageBasePath: "/images/blog/030-cursor-free",
    publishedAt: "2026-05-25",
    ogImage: "ss-01_plan-comparison.png",
    category: "tool",
  },
  "cursor-free-plan-tips": {
    contentId: "03-cursor-free",
    markdownFile: "005-cursor-free-plan-tips.md",
    imageBasePath: "/images/blog/030-cursor-free",
    publishedAt: "2026-05-26",
    ogImage: "ss-01_plan-comparison.png",
    category: "tool",
  },
  "cursor-token-heavy-tasks": {
    contentId: "03-cursor-free",
    markdownFile: "002-cursor-token-heavy-tasks.md",
    imageBasePath: "/images/blog/030-cursor-free",
    publishedAt: "2026-05-27",
    ogImage: "ss-01_plan-comparison.png",
    category: "tool",
  },
  "cursor-agent-pause-recovery-tips": {
    contentId: "03-cursor-free",
    markdownFile: "006-cursor-agent-pause-recovery-tips.md",
    imageBasePath: "/images/blog/030-cursor-free",
    publishedAt: "2026-05-29",
    ogImage: "ss-01_plan-comparison.png",
    category: "tool",
  },
  "cursor-rules-file-tips": {
    contentId: "03-cursor-free",
    markdownFile: "004-cursor-rules-file-tips.md",
    imageBasePath: "/images/blog/030-cursor-free",
    publishedAt: "2026-07-14",
    ogImage: "ss-01_plan-comparison.png",
    category: "tool",
  },
  "chatgpt-account-migration": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "001-chatgpt_account_migration.md",
    imageBasePath: "/images/blog/040-chatgpt_account_migration",
    publishedAt: "2026-05-25",
    ogImage: "ss-01-chatgpt-export.png",
    category: "ai-workflow",
  },
  "chatgpt-migration-md-checklist": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "002-chatgpt-migration-md-checklist.md",
    imageBasePath: "/images/blog/040-chatgpt_account_migration",
    publishedAt: "2026-05-28",
    ogImage: "ss-01-chatgpt-export.png",
    category: "ai-workflow",
  },
  "chatgpt-smartphone-account-migration-tips": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "003-chatgpt-smartphone-account-migration-tips.md",
    imageBasePath: "/images/blog/040-chatgpt_account_migration",
    publishedAt: "2026-06-07",
    ogImage: "og-smartphone-migration-tips.png",
    category: "ai-workflow",
  },
  "nextjs-image-replace-not-reflecting": {
    contentId: "05-nextjs-image-cache",
    markdownFile: "001-nextjs-image-replace-not-reflecting-tips.md",
    imageBasePath: "/images/blog/05-nextjs-image-cache",
    publishedAt: "2026-05-28",
    ogImage: "og.png",
    category: "tool",
  },
  "nextjs-canonical-settings-tips": {
    contentId: "01-site-launch",
    markdownFile: "005-canonical-settings-tips.md",
    imageBasePath: "/images/blog/01-site-launch",
    publishedAt: "2026-05-28",
    ogImage: "og.png",
    category: "devops",
  },
  "nextjs-og-image-fallback-tips": {
    contentId: "01-site-launch",
    markdownFile: "006-og-image-fallback-tips.md",
    imageBasePath: "/images/blog/01-site-launch",
    publishedAt: "2026-05-29",
    ogImage: "og.png",
    category: "devops",
  },
  "nextjs-vercel-preview-check-tips": {
    contentId: "01-site-launch",
    markdownFile: "007-vercel-preview-check-tips.md",
    imageBasePath: "/images/blog/01-site-launch",
    publishedAt: "2026-05-29",
    ogImage: "og.png",
    category: "devops",
  },
  "chatgpt-context-upload-order": {
    contentId: "06-chatgpt-how-to",
    markdownFile: "001-chatgpt-context-order-tips.md",
    imageBasePath: "/images/blog/06-chatgpt-how-to",
    publishedAt: "2026-05-28",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "ai-chat-context-reset-tips": {
    contentId: "06-chatgpt-how-to",
    markdownFile: "002-ai-chat-context-reset-tips.md",
    imageBasePath: "/images/blog/06-chatgpt-how-to",
    publishedAt: "2026-05-29",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-new-chat-template": {
    contentId: "06-chatgpt-how-to",
    markdownFile: "003-chatgpt-new-chat-template.md",
    imageBasePath: "/images/blog/06-chatgpt-how-to",
    publishedAt: "2026-06-02",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "compare-ai-models-opus48-tips": {
    contentId: "20-investigate-something",
    markdownFile: "200-compare-ai-models-opus48-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-05-29",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-ask-mode-tips": {
    contentId: "03-cursor-free",
    markdownFile: "007-cursor-ask-mode-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-05-30",
    ogImage: "og.png",
    category: "tool",
  },
  "context-repost-tips": {
    contentId: "20-investigate-something",
    markdownFile: "202-context-repost-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-05-30",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "fallback-tips": {
    contentId: "20-investigate-something",
    markdownFile: "203-fallback-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-05-30",
    ogImage: "og.png",
    category: "tool",
  },
  "obsidian-dashboard-focus-tips": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "012-obsidian-dashboard-focus-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-05-30",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "hub-series-update-timing-tips": {
    contentId: "08-new-domain-seo",
    markdownFile: "012-hub-series-update-timing.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-05-31",
    ogImage: "og.png",
    category: "devops",
  },
  "dailynote-context-compression": {
    contentId: "07-daily-note-obsidian",
    markdownFile: "001-dailynote-context-compression.md",
    imageBasePath: "/images/blog/07-daily-note-obsidian",
    publishedAt: "2026-05-31",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "dailynote-ai-log-source-reading-order": {
    contentId: "07-daily-note-obsidian",
    markdownFile: "002-dailynote-ai-log-source-reading-order.md",
    imageBasePath: "/images/blog/07-daily-note-obsidian",
    publishedAt: "2026-05-31",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "new-domain-seo-timeline-tips": {
    contentId: "08-new-domain-seo",
    markdownFile: "009-new-domain-seo-timeline.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-05-31",
    ogImage: "og.png",
    category: "devops",
  },
  "cursor-reference-file-prompt-tips": {
    contentId: "03-cursor-free",
    markdownFile: "008-cursor-reference-file-prompt-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-01",
    ogImage: "og.png",
    category: "tool",
  },
  "gpt-claude-two-stage-ai-workflow-tips": {
    contentId: "20-investigate-something",
    markdownFile: "208-gpt-claude-two-stage-ai-workflow-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-01",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-refactor-judgment-before-apply-tips": {
    contentId: "03-cursor-free",
    markdownFile: "009-cursor-refactor-judgment-before-apply-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-01",
    ogImage: "og.png",
    category: "tool",
  },
  "new-domain-seo-trouble-keyword-strategy-tips": {
    contentId: "08-new-domain-seo",
    markdownFile: "010-new-domain-seo-trouble-keyword-strategy-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-01",
    ogImage: "og.png",
    category: "devops",
  },
  "curl-localhost-api-check": {
    contentId: "20-investigate-something",
    markdownFile: "211-curl-localhost-api-check.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-02",
    ogImage: "og.png",
    category: "devops",
  },
  "gsc-index-count-new-domain": {
    contentId: "08-new-domain-seo",
    markdownFile: "002-gsc-index-count-new-domain.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-02",
    ogImage: "og.png",
    category: "devops",
  },
  "gsc-detected-not-indexed": {
    contentId: "08-new-domain-seo",
    markdownFile: "003-gsc-detected-not-indexed.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-02",
    ogImage: "og.png",
    category: "devops",
  },
  "3layer-content-strategy-tips": {
    contentId: "08-new-domain-seo",
    markdownFile: "011-tips-3layer-content-strategy.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-03",
    ogImage: "og.png",
    category: "devops",
  },
  "curl-nextjs-cors-tips": {
    contentId: "20-investigate-something",
    markdownFile: "215-tips-curl-nextjs-cors.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-03",
    ogImage: "og.png",
    category: "devops",
  },
  "new-domain-seo-troubleshooting-4steps": {
    contentId: "08-new-domain-seo",
    markdownFile: "001-tips-new-domain-seo-4steps.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-03",
    ogImage: "og.png",
    category: "devops",
  },
  "sitemap-index-checklist-tips": {
    contentId: "08-new-domain-seo",
    markdownFile: "004-tips-sitemap-index-checklist.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-03",
    ogImage: "og.png",
    category: "devops",
  },
  "gsc-image-url-404-tips": {
    contentId: "08-new-domain-seo",
    markdownFile: "005-gsc-image-url-404-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-04",
    ogImage: "og.png",
    category: "devops",
  },
  "gsc-og-image-404-fixed-verify": {
    contentId: "08-new-domain-seo",
    markdownFile: "008-gsc-og-image-404-fixed-verify.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-04",
    ogImage: "og.png",
    category: "devops",
  },
  "deploy-check-image-basepath-og-file": {
    contentId: "08-new-domain-seo",
    markdownFile: "007-deploy-check-image-basepath-og-file.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-04",
    ogImage: "og.png",
    category: "devops",
  },
  "gsc-image-404-vs-default-og-fallback": {
    contentId: "08-new-domain-seo",
    markdownFile: "006-gsc-image-404-vs-default-og-fallback.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-04",
    ogImage: "og.png",
    category: "devops",
  },
  "blog-page-size-15-tips": {
    contentId: "01-site-launch",
    markdownFile: "010-blog-page-size-15-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-05",
    ogImage: "og.png",
    category: "devops",
  },
  "markdown-internal-link-relative-path-tips": {
    contentId: "01-site-launch",
    markdownFile: "011-markdown-internal-link-relative-path-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-05",
    ogImage: "og.png",
    category: "devops",
  },
  "cursor-plan-mode-modify-before-build-tips": {
    contentId: "03-cursor-free",
    markdownFile: "010-cursor-plan-mode-modify-before-build-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-05",
    ogImage: "og.png",
    category: "tool",
  },
  "internal-link-draft-label-update": {
    contentId: "20-investigate-something",
    markdownFile: "226-internal-link-draft-label-update.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-06",
    ogImage: "og.png",
    category: "devops",
  },
  "gsc-article-ui-change-disclaimer": {
    contentId: "20-investigate-something",
    markdownFile: "227-gsc-article-ui-change-disclaimer.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-06",
    ogImage: "og.png",
    category: "devops",
  },
  "source-md-note-disclaimer-reflection": {
    contentId: "20-investigate-something",
    markdownFile: "228-source-md-note-disclaimer-reflection.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-06",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "posts-ts-auto-reflect-sitemap-blog-list": {
    contentId: "20-investigate-something",
    markdownFile: "229-posts-ts-auto-reflect-sitemap-blog-list.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-07",
    ogImage: "og.png",
    category: "devops",
  },
  "cross-link-reverse-update-after-publish": {
    contentId: "20-investigate-something",
    markdownFile: "230-cross-link-reverse-update-after-publish.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-07",
    ogImage: "og.png",
    category: "devops",
  },
  "spoke-article-internal-link-role-separation": {
    contentId: "20-investigate-something",
    markdownFile: "231-spoke-article-internal-link-role-separation.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-07",
    ogImage: "og.png",
    category: "devops",
  },
  "npm-run-build-http200-sitemap-og-fallback-check": {
    contentId: "20-investigate-something",
    markdownFile: "232-npm-run-build-http200-sitemap-og-fallback-check.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-07",
    ogImage: "og.png",
    category: "devops",
  },
  "unpublished-link-after-slug-confirmed": {
    contentId: "20-investigate-something",
    markdownFile: "233-unpublished-link-after-slug-confirmed.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-08",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "hub-article-as-reference-axis-for-series": {
    contentId: "20-investigate-something",
    markdownFile: "234-hub-article-as-reference-axis-for-series.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-08",
    ogImage: "og.png",
    category: "devops",
  },
  "resolve-og-image-fallback-to-default": {
    contentId: "20-investigate-something",
    markdownFile: "235-resolve-og-image-fallback-to-default.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-08",
    ogImage: "og.png",
    category: "devops",
  },
  "gsc-index-last-updated-not-a-failure": {
    contentId: "20-investigate-something",
    markdownFile: "236-gsc-index-last-updated-not-a-failure.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-08",
    ogImage: "og.png",
    category: "devops",
  },
  "ai-chat-slot-separation-tips": {
    contentId: "20-investigate-something",
    markdownFile: "237-ai-chat-slot-separation-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-09",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-agent-scope-tips": {
    contentId: "03-cursor-free",
    markdownFile: "021-cursor-agent-scope-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-09",
    ogImage: "og.png",
    category: "tool",
  },
  "hub-spoke-link-update-tips": {
    contentId: "20-investigate-something",
    markdownFile: "239-hub-spoke-link-update-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-09",
    ogImage: "og.png",
    category: "devops",
  },
  "series-ts-spoke-add-tips": {
    contentId: "20-investigate-something",
    markdownFile: "240-series-ts-spoke-add-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-09",
    ogImage: "og.png",
    category: "devops",
  },
  "gsc-index-request-daily-limit": {
    contentId: "20-investigate-something",
    markdownFile: "241-gsc-index-request-daily-limit.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-10",
    ogImage: "og.png",
    category: "devops",
  },
  "gsc-image-404-request-article-url": {
    contentId: "20-investigate-something",
    markdownFile: "242-gsc-image-404-request-article-url.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-10",
    ogImage: "og.png",
    category: "devops",
  },
  "og-image-json-ld-pagesource-check": {
    contentId: "20-investigate-something",
    markdownFile: "243-og-image-json-ld-pagesource-check.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-10",
    ogImage: "og.png",
    category: "devops",
  },
  "cursor-agent-gh-pr-create-fill": {
    contentId: "03-cursor-free",
    markdownFile: "018-cursor-agent-gh-pr-create-fill.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-11",
    ogImage: "og.png",
    category: "tool",
  },
  "x-og-image-404-cache": {
    contentId: "20-investigate-something",
    markdownFile: "245-x-og-image-404-cache.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-11",
    ogImage: "og.png",
    category: "devops",
  },
  "gsc-redirect-domain-normalization": {
    contentId: "08-new-domain-seo",
    markdownFile: "014-gsc-redirect-domain-normalization.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-11",
    ogImage: "og.png",
    category: "devops",
  },
  "gsc-redirect-loop-check-tips": {
    contentId: "08-new-domain-seo",
    markdownFile: "015-gsc-redirect-loop-check-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-12",
    ogImage: "og.png",
    category: "devops",
  },
  "gsc-index-weekly-check-tips": {
    contentId: "08-new-domain-seo",
    markdownFile: "019-gsc-index-weekly-check-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-12",
    ogImage: "og.png",
    category: "devops",
  },
  "new-domain-canonical-www-check-tips": {
    contentId: "08-new-domain-seo",
    markdownFile: "016-new-domain-canonical-www-check-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-12",
    ogImage: "og.png",
    category: "devops",
  },
  "chatgpt-og-image-prompt-design": {
    contentId: "20-investigate-something",
    markdownFile: "250-chatgpt-og-image-prompt-design.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-13",
    ogImage: "og.png",
    category: "tool",
  },
  "new-domain-ymyl-avoid": {
    contentId: "08-new-domain-seo",
    markdownFile: "020-new-domain-ymyl-avoid.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-13",
    ogImage: "og.png",
    category: "devops",
  },
  "gsc-index-request-priority-url": {
    contentId: "08-new-domain-seo",
    markdownFile: "018-gsc-index-request-priority-url.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-13",
    ogImage: "og.png",
    category: "devops",
  },
  "vercel-domain-connection-tips": {
    contentId: "01-site-launch",
    markdownFile: "009-vercel-domain-connection-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-14",
    ogImage: "og.png",
    category: "devops",
  },
  "chatgpt-cursor-claude-role-sharing-tips": {
    contentId: "01-site-launch",
    markdownFile: "008-chatgpt-cursor-claude-role-sharing-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-14",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "git-branch-basic-tips": {
    contentId: "03-cursor-free",
    markdownFile: "011-git-branch-basic-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-14",
    ogImage: "og.png",
    category: "tool",
  },
  "claude-draft-review-before-publish": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "010-claude-draft-review-before-publish.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-15",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-slow-troubleshoot-tips": {
    contentId: "03-cursor-free",
    markdownFile: "019-cursor-slow-troubleshoot-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-15",
    ogImage: "og.png",
    category: "tool",
  },
  "chatgpt-share-link-ai-cannot-read-url": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "004-chatgpt-share-link-ai-cannot-read-url.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-15",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "nextjs-blog-date-mismatch-fix": {
    contentId: "20-investigate-something",
    markdownFile: "259-nextjs-blog-date-mismatch-fix.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-16",
    ogImage: "og.png",
    category: "devops",
  },
  "obsidian-mode-live-preview-source": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "011-obsidian-mode-live-preview-source.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-16",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "nextjs-blog-markdown-management": {
    contentId: "20-investigate-something",
    markdownFile: "261-nextjs-blog-markdown-management.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-16",
    ogImage: "og.png",
    category: "devops",
  },
  "push-before-npm-run-build": {
    contentId: "20-investigate-something",
    markdownFile: "262-push-before-npm-run-build.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-17",
    ogImage: "og.png",
    category: "devops",
  },
  "github-push-checklist": {
    contentId: "20-investigate-something",
    markdownFile: "263-github-push-checklist.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-17",
    ogImage: "og.png",
    category: "devops",
  },
  "obsidian-advanced-tables-source-mode": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "013-obsidian-advanced-tables-source-mode.md",
    imageBasePath: "/images/blog/02-claude-obsidian-workflow",
    publishedAt: "2026-06-17",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "obsidian-nested-codeblock-backticks": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "014-obsidian-nested-codeblock-backticks.md",
    imageBasePath: "/images/blog/02-claude-obsidian-workflow",
    publishedAt: "2026-06-18",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "git-branch-rename-local": {
    contentId: "20-investigate-something",
    markdownFile: "266-git-branch-rename-local.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-18",
    ogImage: "og.png",
    category: "devops",
  },
  "markdown-table-linebreak": {
    contentId: "20-investigate-something",
    markdownFile: "267-markdown-table-linebreak.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-18",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "claude-long-text-split-tips": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "015-claude-long-text-split-tips.md",
    imageBasePath: "/images/blog/02-claude-obsidian-workflow",
    publishedAt: "2026-06-19",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "obsidian-internal-link-candidate-missing": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "016-obsidian-internal-link-candidate-missing.md",
    imageBasePath: "/images/blog/02-claude-obsidian-workflow",
    publishedAt: "2026-06-19",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-search-history-account-migration": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "005-chatgpt-search-history-account-migration.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-19",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-cursorignore-token-context": {
    contentId: "03-cursor-free",
    markdownFile: "012-cursor-cursorignore-token-context.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-20",
    ogImage: "og.png",
    category: "tool",
  },
  "gsc-sitemap-full-url-resubmit": {
    contentId: "20-investigate-something",
    markdownFile: "272-gsc-sitemap-full-url-resubmit.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-20",
    ogImage: "og.png",
    category: "devops",
  },
  "cursor-implementation-plan-file-request": {
    contentId: "03-cursor-free",
    markdownFile: "013-cursor-implementation-plan-file-request.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-20",
    ogImage: "og.png",
    category: "tool",
  },
  "obsidian-dataview-dot-filename-fix": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "017-obsidian-dataview-dot-filename-fix.md",
    imageBasePath: "/images/blog/02-claude-obsidian-workflow",
    publishedAt: "2026-06-20",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "ai-output-scroll-container": {
    contentId: "20-investigate-something",
    markdownFile: "275-ai-output-scroll-container.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-21",
    ogImage: "og.png",
    category: "devops",
  },
  "ai-debug-keep-raw-error-info": {
    contentId: "03-cursor-free",
    markdownFile: "014-ai-debug-keep-raw-error-info.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-21",
    ogImage: "og.png",
    category: "tool",
  },
  "ai-prompt-beginner-friendly": {
    contentId: "03-cursor-free",
    markdownFile: "015-ai-prompt-beginner-friendly.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-21",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "gsc-smartphone-googlebot-not-error": {
    contentId: "08-new-domain-seo",
    markdownFile: "021-gsc-smartphone-googlebot-not-error.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-22",
    ogImage: "og.png",
    category: "devops",
  },
  "windows-emoji-panel-shortcut": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "018-windows-emoji-panel-shortcut.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-22",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "decision-flow-codeblock-troubleshooting": {
    contentId: "20-investigate-something",
    markdownFile: "280-decision-flow-codeblock-troubleshooting.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-22",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-pro-total-usage-limit-reached": {
    contentId: "03-cursor-free",
    markdownFile: "003-cursor-pro-total-usage-limit-reached.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-23",
    ogImage: "og.png",
    category: "tool",
  },
  "app-router-scroll-to-all-articles": {
    contentId: "01-site-launch",
    markdownFile: "014-app-router-scroll-to-all-articles.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-23",
    ogImage: "og.png",
    category: "devops",
  },
  "reuse-same-image-alt-text": {
    contentId: "01-site-launch",
    markdownFile: "013-reuse-same-image-alt-text.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-23",
    ogImage: "og.png",
    category: "devops",
  },
  "nextjs-turbopack-nft-trace-warning": {
    contentId: "20-investigate-something",
    markdownFile: "284-nextjs-turbopack-nft-trace-warning.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-24",
    ogImage: "og.png",
    category: "devops",
  },
  "nextjs-public-images-absolute-path": {
    contentId: "01-site-launch",
    markdownFile: "012-nextjs-public-images-absolute-path.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-24",
    ogImage: "og.png",
    category: "devops",
  },
  "chatgpt-custom-instructions-for-beginners": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "006-chatgpt-custom-instructions-for-beginners.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-24",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-pre-dev-checklist": {
    contentId: "03-cursor-free",
    markdownFile: "016-cursor-pre-dev-checklist.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-25",
    ogImage: "og.png",
    category: "tool",
  },
  "cursor-error-triage-checklist": {
    contentId: "03-cursor-free",
    markdownFile: "017-cursor-error-triage-checklist.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-25",
    ogImage: "og.png",
    category: "tool",
  },
  "canonical-tag-setup-location": {
    contentId: "08-new-domain-seo",
    markdownFile: "017-canonical-tag-setup-location.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-25",
    ogImage: "og.png",
    category: "devops",
  },
  "chatgpt-account-deletion-checklist": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "015-chatgpt-account-deletion-checklist.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-26",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-file-check-before-edit": {
    contentId: "03-cursor-free",
    markdownFile: "032-cursor-file-check-before-edit.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-26",
    ogImage: "og.png",
    category: "tool",
  },
  "cursor-terminal-error-first-3-lines": {
    contentId: "03-cursor-free",
    markdownFile: "033-cursor-terminal-error-first-3-lines.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-26",
    ogImage: "og.png",
    category: "tool",
  },
  "cursor-diff-check-tips": {
    contentId: "03-cursor-free",
    markdownFile: "030-cursor-diff-check-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-27",
    ogImage: "og.png",
    category: "tool",
  },
  "cursor-repeated-error-tips": {
    contentId: "03-cursor-free",
    markdownFile: "034-cursor-repeated-error-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-27",
    ogImage: "og.png",
    category: "tool",
  },
  "chatgpt-account-migration-checklist": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "007-chatgpt-account-migration-checklist.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-27",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "ai-input-structuring-tips": {
    contentId: "20-investigate-something",
    markdownFile: "296-ai-input-structuring-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-28",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "obsidian-table-center-align": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "019-obsidian-table-center-align.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-28",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-project-vs-normal-chat": {
    contentId: "20-investigate-something",
    markdownFile: "298-chatgpt-project-vs-normal-chat.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-28",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "ai-tools-comparison": {
    contentId: "09-ai-tools-comparison",
    markdownFile: "001-ai-tools-comparison.md",
    imageBasePath: "/images/blog/09-ai-tools-comparison",
    publishedAt: "2026-06-28",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-chatgpt-usecase-comparison": {
    contentId: "09-ai-tools-comparison",
    markdownFile: "002-cursor-chatgpt-usecase-comparison.md",
    imageBasePath: "/images/blog/09-ai-tools-comparison",
    publishedAt: "2026-06-28",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-claude-usecase-comparison": {
    contentId: "09-ai-tools-comparison",
    markdownFile: "003-cursor-claude-usecase-comparison.md",
    imageBasePath: "/images/blog/09-ai-tools-comparison",
    publishedAt: "2026-06-28",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-claude-comparison": {
    contentId: "09-ai-tools-comparison",
    markdownFile: "004-chatgpt-claude-comparison.md",
    imageBasePath: "/images/blog/09-ai-tools-comparison",
    publishedAt: "2026-06-28",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-plus-free-comparison": {
    contentId: "09-ai-tools-comparison",
    markdownFile: "005-chatgpt-plus-free-comparison.md",
    imageBasePath: "/images/blog/09-ai-tools-comparison",
    publishedAt: "2026-06-29",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "claude-pro-free-comparison": {
    contentId: "09-ai-tools-comparison",
    markdownFile: "006-claude-pro-free-comparison.md",
    imageBasePath: "/images/blog/09-ai-tools-comparison",
    publishedAt: "2026-06-29",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-strengths-weaknesses": {
    contentId: "09-ai-tools-comparison",
    markdownFile: "007-cursor-strengths-weaknesses.md",
    imageBasePath: "/images/blog/09-ai-tools-comparison",
    publishedAt: "2026-06-29",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "vercel-production-not-reflecting-tips": {
    contentId: "01-site-launch",
    markdownFile: "015-vercel-production-not-reflecting-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-30",
    ogImage: "og.png",
    category: "devops",
  },
  "vercel-promote-to-production-tips": {
    contentId: "01-site-launch",
    markdownFile: "016-vercel-promote-to-production-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-30",
    ogImage: "og.png",
    category: "devops",
  },
  "vercel-auto-deploy-not-working-tips": {
    contentId: "01-site-launch",
    markdownFile: "017-vercel-auto-deploy-not-working-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-06-30",
    ogImage: "og.png",
    category: "devops",
  },
  "npm-run-build-reason": {
    contentId: "20-investigate-something",
    markdownFile: "305-npm-run-build-reason.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-01",
    ogImage: "og.png",
    category: "devops",
  },
  "obsidian-checkmark-input": {
    contentId: "20-investigate-something",
    markdownFile: "306-obsidian-checkmark-input.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-01",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "create-next-app-current-folder": {
    contentId: "01-site-launch",
    markdownFile: "018-create-next-app-current-folder.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-01",
    ogImage: "og.png",
    category: "devops",
  },
  "ai-blog-writing-workflow-source-to-publish": {
    contentId: "20-investigate-something",
    markdownFile: "308-ai-blog-writing-workflow-source-to-publish.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-01",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-history-missing-device-change": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "008-chatgpt-history-missing-device-change.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-02",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "obsidian-table-broken-live-preview-fix": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "022-obsidian-table-broken-live-preview-fix.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-02",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "obsidian-checkmark-to-checkbox": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "023-obsidian-checkmark-to-checkbox.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-02",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-claude-blog-writing-howto": {
    contentId: "20-investigate-something",
    markdownFile: "312-chatgpt-claude-blog-writing-howto.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-02",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-migration-memory-check": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "009-chatgpt-migration-memory-check.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-03",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-migration-plus-check": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "010-chatgpt-migration-plus-check.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-03",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-migration-2fa-check": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "011-chatgpt-migration-2fa-check.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-03",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "obsidian-checkbox-uncheck-3steps": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "024-obsidian-checkbox-uncheck-3steps.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-04",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "comparison-article-weak-link-funnel": {
    contentId: "20-investigate-something",
    markdownFile: "317-comparison-article-weak-link-funnel.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-04",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "react-markdown-affiliate-link-empty-fix": {
    contentId: "20-investigate-something",
    markdownFile: "318-react-markdown-affiliate-link-empty-fix.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-04",
    ogImage: "og.png",
    category: "devops",
  },
  "multi-generative-ai-comparison-business": {
    contentId: "09-ai-tools-comparison",
    markdownFile: "008-multi-generative-ai-comparison-business.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-04",
    ogImage: "319-og.png",
    category: "ai-workflow",
    layout: "rich-toc",
  },
  "nextjs-301-redirect-legacy-url-tips": {
    contentId: "01-site-launch",
    markdownFile: "019-nextjs-301-redirect-legacy-url-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-05",
    ogImage: "og.png",
    category: "devops",
  },
  "chatgpt-migration-2fa-authenticator-tips": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "012-chatgpt-migration-2fa-authenticator-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-05",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-plus-ios-android-transfer-tips": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "013-chatgpt-plus-ios-android-transfer-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-05",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "ai-basics-before-chatgpt-claude-checklist": {
    contentId: "09-ai-tools-comparison",
    markdownFile: "009-ai-basics-before-chatgpt-claude-checklist.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-05",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-chatgpt-review-tips": {
    contentId: "03-cursor-free",
    markdownFile: "036-cursor-chatgpt-review-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-06",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-long-text-h1-h2-format-tips": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "014-chatgpt-long-text-h1-h2-format-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-06",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-plan-mode-md-save-tips": {
    contentId: "03-cursor-free",
    markdownFile: "023-cursor-plan-mode-md-save-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-06",
    ogImage: "og.png",
    category: "tool",
  },
  "ai-prompt-engineering-beginner-roadmap": {
    contentId: "20-investigate-something",
    markdownFile: "327-ai-prompt-engineering-beginner-roadmap.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-07",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-claude-prompt-writing-comparison": {
    contentId: "09-ai-tools-comparison",
    markdownFile: "010-chatgpt-claude-prompt-writing-comparison.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-08",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "git-commit-m-space-mistake-empty-commit": {
    contentId: "20-investigate-something",
    markdownFile: "332-git-commit-m-space-mistake-empty-commit.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-08",
    ogImage: "og.png",
    category: "devops",
  },
  "obsidian-ai-log-codeblock-fix": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "020-obsidian-ai-log-codeblock-fix.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-08",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "obsidian-wikilink-file-heading-syntax": {
    contentId: "02-claude-obsidian-workflow",
    markdownFile: "021-obsidian-wikilink-file-heading-syntax.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-08",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "affiliate-marker-only-no-raw-url": {
    contentId: "20-investigate-something",
    markdownFile: "330-affiliate-marker-only-no-raw-url.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-07",
    ogImage: "og.png",
    category: "devops",
  },
  "accesstrade-affiliate-setup-checklist": {
    contentId: "20-investigate-something",
    markdownFile: "328-accesstrade-affiliate-setup-checklist.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-07",
    ogImage: "og.png",
    category: "devops",
  },
  "comparison-direct-affiliate-blocked-slugs": {
    contentId: "20-investigate-something",
    markdownFile: "329-comparison-direct-affiliate-blocked-slugs.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-07",
    ogImage: "og.png",
    category: "devops",
  },
  "chatgpt-device-change-handover-tips": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "016-chatgpt-device-change-handover-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-09",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-account-migration-3-checkpoints": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "018-chatgpt-account-migration-3-checkpoints.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-09",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-usage-limit-reached-3-steps": {
    contentId: "03-cursor-free",
    markdownFile: "027-cursor-usage-limit-reached-3-steps.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-09",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-claude-business-writing-comparison": {
    contentId: "09-ai-tools-comparison",
    markdownFile: "011-chatgpt-claude-business-writing-comparison.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-09",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "ai-request-evaluation-axis-tips": {
    contentId: "20-investigate-something",
    markdownFile: "339-ai-request-evaluation-axis-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-10",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "nextjs-app-page-top-edit-tips": {
    contentId: "20-investigate-something",
    markdownFile: "340-nextjs-app-page-top-edit-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-10",
    ogImage: "og.png",
    category: "devops",
  },
  "cursor-workspace-multi-repo-tips": {
    contentId: "03-cursor-free",
    markdownFile: "025-cursor-workspace-multi-repo-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-10",
    ogImage: "og.png",
    category: "tool",
  },
  "team-ai-portal-vs-comparison-tool-guide": {
    contentId: "20-investigate-something",
    markdownFile: "342-team-ai-portal-vs-comparison-tool-guide.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-10",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "git-stash-pop-tips": {
    contentId: "03-cursor-free",
    markdownFile: "035-git-stash-pop-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-11",
    ogImage: "og.png",
    category: "tool",
  },
  "cursor-diff-shortcut-tips": {
    contentId: "03-cursor-free",
    markdownFile: "031-cursor-diff-shortcut-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-11",
    ogImage: "og.png",
    category: "tool",
  },
  "cursor-agent-failed-tips": {
    contentId: "03-cursor-free",
    markdownFile: "028-cursor-agent-failed-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-11",
    ogImage: "og.png",
    category: "tool",
  },
  "cursor-windows-slow-check-tips": {
    contentId: "03-cursor-free",
    markdownFile: "029-cursor-windows-slow-check-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-12",
    ogImage: "og.png",
    category: "tool",
  },
  "chatgpt-pdf-attachment-order-tips": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "019-chatgpt-pdf-attachment-order-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-12",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "claude-cursor-2step-workflow-tips": {
    contentId: "03-cursor-free",
    markdownFile: "024-claude-cursor-2step-workflow-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-12",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-theme-color-change-tips": {
    contentId: "03-cursor-free",
    markdownFile: "037-cursor-theme-color-change-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-13",
    ogImage: "og.png",
    category: "tool",
  },
  "cursor-auto-manual-model-quality-tips": {
    contentId: "03-cursor-free",
    markdownFile: "026-cursor-auto-manual-model-quality-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-13",
    ogImage: "og.png",
    category: "tool",
  },
  "tips-publish-backlink-checklist": {
    contentId: "20-investigate-something",
    markdownFile: "351-tips-publish-backlink-checklist.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-13",
    ogImage: "og.png",
    category: "devops",
  },
  "gsc-same-day-publish-cross-link-tips": {
    contentId: "20-investigate-something",
    markdownFile: "352-gsc-same-day-publish-cross-link-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-14",
    ogImage: "og.png",
    category: "devops",
  },
  "ai-rewrite-4stage-claude-chatgpt-tips": {
    contentId: "20-investigate-something",
    markdownFile: "353-ai-rewrite-4stage-claude-chatgpt-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-14",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chat-slot-initial-prompt-tips": {
    contentId: "20-investigate-something",
    markdownFile: "354-chat-slot-initial-prompt-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-14",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "free-ai-seminar-checklist-before-booking-tips": {
    contentId: "20-investigate-something",
    markdownFile: "355-free-ai-seminar-checklist-before-booking-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-14",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-claude-same-prompt-comparison-template-tips": {
    contentId: "20-investigate-something",
    markdownFile: "356-chatgpt-claude-same-prompt-comparison-template-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-14",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-projects-vs-claude-longtext-start-tips": {
    contentId: "20-investigate-something",
    markdownFile: "357-chatgpt-projects-vs-claude-longtext-start-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-14",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "claude-longtext-3line-summary-before-paste-tips": {
    contentId: "20-investigate-something",
    markdownFile: "358-claude-longtext-3line-summary-before-paste-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-14",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "doraverse-trial-btob-checklist-tips": {
    contentId: "20-investigate-something",
    markdownFile: "359-doraverse-trial-btob-checklist-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-14",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-recommended-settings-tips": {
    contentId: "03-cursor-free",
    markdownFile: "020-cursor-recommended-settings-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-14",
    ogImage: "og.png",
    category: "tool",
  },
  "hub-article-update-frequency-tips": {
    contentId: "20-investigate-something",
    markdownFile: "361-hub-article-update-frequency-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-15",
    ogImage: "og.png",
    category: "devops",
  },
  "cursor-ask-ai-log-tips": {
    contentId: "20-investigate-something",
    markdownFile: "362-cursor-ask-ai-log-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-15",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "obsidian-tips-inbox-published": {
    contentId: "20-investigate-something",
    markdownFile: "363-obsidian-tips-inbox-published.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-15",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-device-change-account-migration-3-points": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "020-chatgpt-device-change-account-migration-3-points.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-16",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-device-change-wrong-login-history-empty": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "021-chatgpt-device-change-wrong-login-history-empty.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-16",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "chatgpt-web-app-login-mismatch-fix": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "022-chatgpt-web-app-login-mismatch-fix.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-16",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "claude-code-guide": {
    contentId: "10-claude-developer",
    markdownFile: "001-claude-code-guide.md",
    imageBasePath: "/images/blog/10-claude-developer",
    publishedAt: "2026-07-16",
    ogImage: "og.png",
    category: "tool",
  },
  "mcp-guide": {
    contentId: "11-mcp",
    markdownFile: "001-mcp-guide.md",
    imageBasePath: "/images/blog/11-mcp",
    publishedAt: "2026-07-16",
    ogImage: "og.png",
    category: "tool",
  },
  "chatgpt-device-change-3-screens-tips": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "017-chatgpt-device-change-3-screens-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-17",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "cursor-agent-unintended-edit-git-restore-tips": {
    contentId: "03-cursor-free",
    markdownFile: "022-cursor-agent-unintended-edit-git-restore-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-17",
    ogImage: "og.png",
    category: "tool",
  },
  "series-ts-get-series-for-post-first-win-same-commit-tips": {
    contentId: "01-site-launch",
    markdownFile: "020-series-ts-get-series-for-post-first-win-same-commit-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-17",
    ogImage: "og.png",
    category: "devops",
  },
  "chatgpt-device-change-google-login-tips": {
    contentId: "04-chatgpt_account_migration",
    markdownFile: "023-chatgpt-device-change-google-login-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-18",
    ogImage: "og.png",
    category: "ai-workflow",
  },
  "1min-tips-ai-seo-fit-tips": {
    contentId: "08-new-domain-seo",
    markdownFile: "022-1min-tips-ai-seo-fit-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-18",
    ogImage: "og.png",
    category: "devops",
  },
  "blog-rewrite-published-date-rule-tips": {
    contentId: "01-site-launch",
    markdownFile: "021-blog-rewrite-published-date-rule-tips.md",
    imageBasePath: "/images/blog/20-investigate-something",
    publishedAt: "2026-07-18",
    ogImage: "og.png",
    category: "devops",
  },
} as const satisfies Record<string, import("./types").BlogPostConfig>;

/** 公開 URL の slug 型（blogPosts のキーから自動生成） */
export type BlogSlug = keyof typeof blogPosts;

export const blogSlugs = Object.keys(blogPosts) as BlogSlug[];

export function isBlogSlug(slug: string): slug is BlogSlug {
  return slug in blogPosts;
}

function buildMarkdownPath(contentId: string, markdownFile: string): string {
  return path.join("content", "blog", contentId, markdownFile);
}

export function getPostMeta(slug: BlogSlug): BlogPostMeta {
  const config = blogPosts[slug];
  return {
    slug,
    ...config,
    markdownPath: buildMarkdownPath(config.contentId, config.markdownFile),
  };
}

export function getAllPostMeta(): BlogPostMeta[] {
  return blogSlugs.map(getPostMeta);
}
